#!/usr/bin/env bash
set -euo pipefail

LUMINA_MICRO_DEMO_BACKEND=${LUMINA_MICRO_DEMO_BACKEND:-ollama} \
LUMINA_MICRO_DEMO_OLLAMA_MODEL=${LUMINA_MICRO_DEMO_OLLAMA_MODEL:-llama3.1:latest} \
LUMINA_MICRO_DEMO_OLLAMA_KEEPALIVE=${LUMINA_MICRO_DEMO_OLLAMA_KEEPALIVE:-5m} \
bash lumina_micro_demo/tools/run_demo_present.sh
